# Your Name or Company
title: Phil Artmann

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: Nullam id dolor id nibh ultricies vehicula ut id elit. Cras mattis consectetur purus sit amet fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum.

# Add your social links
social:
  - platform: rhetoric training
    url: https://head-coaches.de
  - platform: rhetoric podcast
    url: https://getahead-podcast.de
  - platform: comedy & music
    url: https://maxundpille.de
  - platform: spotify
    url: https://open.spotify.com/artist/233R46NbvEKc9uY3S29UuH?si=g_ToWSvySaKW0azmoc5-hw
  - platform: story podcast
    url: https://nachtschatten-podcast.de
  - platform: cv
    url: assets/git_cheat_sheet.pdf

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni"
markdown: kramdown
sharing_image: share.jpg
  # google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
