# Your Name or Company
title: Phil Artmann

# Description of your website. This is used for social sharing.
description:  Phil Artmann's website linking to all his projects.

# A brief blurb about yourself
content: rhetoric and communications trainer, german linguistic graduate, postgrad student (speech communication and rhetoric), media-it graduate, developer, podcaster, geek, apple enthusiast, linux lover, privacy advocate, crypto nerd, never-ending learner, book worm, photographer, comedian & musician. language builds reality. let's change the world.

# Add your social links
social:
  - platform: rhetoric training
    url: https://head-coaches.de
  - platform: rhetoric podcast
    url: https://getahead-podcast.de
  - platform: comedy & music
    url: https://maxundpille.de
  - platform: spotify
    url: https://open.spotify.com/artist/233R46NbvEKc9uY3S29UuH?si=g_ToWSvySaKW0azmoc5-hw
  - platform: story podcast
    url: https://nachtschatten-podcast.de
  - platform: linkedin
    url: https://www.linkedin.com/in/philipp-b-n-artmann-540317155/
  - platform: twitter
    url: https://twitter.com/artphil_
  - platform: instagram
    url: https://www.instagram.com/artphil/
  - platform: github
    url: https://github.com/PilleA
  - platform: gitlab
    url: https://gitlab.com/PilleA
  - platform: bitcoin tip jar
    url: bitcoin:bc1qekaltrst0rk4su4dmg7lw66u65kvjyjjndsvca?message=philartmann&time=1628268032
  - platform: cv (german)
    url: assets/artmann_online.pdf
  - platform: gpg key
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x65262e0498609997d581fd8768ca52c1821757d4
  - platform: contact
    url: mailto:p.artmann@mailbox.org

# General settings
url: https://philartmann.de
  # baseurl: "/docs"
markdown: kramdown
sharing_image: share.jpg
  # google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
